### ISSUE TITLE
Configure a .eslintrc path dynamically based on Project root folder

### ISSUE THREAD

**Issue by ndaljr** [ruanyl/vim-fixmyjs#13]
Hi I was just wondering if it would be possible to set the path of the .eslintrc file dynamically to the root project folder. It would work in the case where different projects have different .eslintrc configurations. Would like to hear your thoughts on the matter. Cheers!

**Comment by ruanyl** [comment]
Hi, it will first look up the `eslintrc` file in the root dir of current project if you don't specify a path. It's kind of 'dynamical' by default.

**Comment by ndaljr** [comment]
Oh I wasn't aware of that. The documentation wasn't explicit about. I thought I was going to have a problem because I thought I would have to have two config files. One for my syntactic and one for my fixjs. Thanks for the clarification!
