### ISSUE TITLE
"Can not find .jshintrc file"

### ISSUE THREAD

**Issue by westandy** [ruanyl/vim-fixmyjs#8]
I get "Can not find .jshintrc file" on :w with your plugin.  And the file does not get changed.  

I have eslint installed globally (npm install -g eslint)

My .vimrc is like so:

set nocompatible
filetype off 

" Set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()

" alternatively, pass a path where Vundle should install plugins
" call vundle#begin('~/some/path/here')
" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Bundle 'ruanyl/vim-fixmyjs'
Plugin 'leafgarland/typescript-vim'

" All of your Plugins must be added before the following line
call vundle#end() " required
" end Vundle

filetype plugin indent on    " required
set tabstop=3 shiftwidth=3 smarttab
set number

syntax on
au Bufread,BufNewFile *.ts setfiletype  typescript
autocmd QuickFixCmdPost [^l]* nested cwindow
autocmd QuickFixCmdPost    l* nested lwindow

au BufWritePre *.js :Fixmyjs
au BufWritePre *.jsx :Fixmyjs

noremap <Leader><Leader>f :Fixmyjs<CR>
"

I'm not a vim guru, so I apologize if it's just me doing something dumb in my .vimrc.

**Comment by ruanyl** [comment]
Hi @westandy , sorry for the the confused Warning message, it's actually not `jshinrc`, it should be the `rc` file depends on which lint tool you are using. for eslint, it's `eslintrc` by default.

The plugin will first looking for a `.eslintrc` file in your project root folder(based on .git file). if it can not find it, it will fall back to you home dir `~/.eslintrc`.

When you see this warning message, it means the plugin can not find the file in both the location.

So you could add an `.eslintrc` in either your project root dir, or you home dir to solve this problem.

**Comment by westandy** [comment]
I have an .eslintrc.json from the eslint --init command.  I will try making a soft link to the json.

Also, in your README, it states that it is looking for either ~/.rc or ~/.vim/.rc to have the .eslintrc file.  

<sarcasm>Aren't config files the greatest?</sarcasm>

**Comment by westandy** [comment]
The soft link to .eslintrc.json worked (ln -s .eslintrc.json .eslintrc)
