### ISSUE TITLE
Switched to --save-dev eslint, instead of -g for npm.  

### ISSUE THREAD

**Issue by westandy** [ruanyl/vim-fixmyjs#9]
After moving my eslint npm install to --save-dev instead of -g, what do i need to set g:fixmyjs_engine to?

I tried this on line 29 in the plugin file, fixmyjs.vim:
 let g:fixmyjs_engine = '$HOME/myRepo/node_modules/.bin/eslint' 

but this just causes even more issues.

Thanks!

**Comment by ruanyl** [comment]
Thanks for the comment, I should do a bit update so that it will handle custom path to: for example `eslint`. `g:fixmyjs_engine` actually doesn't work in this case, sorry about that.

**Comment by westandy** [comment]
No problem.  If I knew how to fix it myself, I would gladly do it.

**Comment by ruanyl** [comment]
@westandy I made a fix to this issue, please find the updated README :)
